name       : nano
version    : '6.1'
release    : 130
source     :
    - https://www.nano-editor.org/dist/v6/nano-6.1.tar.xz : 3d57ec893fbfded12665b7f0d563d74431fc43abeaccacedea23b66af704db40
homepage   : https://www.nano-editor.org
license    : GPL-3.0-or-later
component  : system.devel
summary    : Small, friendly text editor inspired by Pico
description: |
    GNU nano is an easy-to-use text editor originally designed as a replacement for Pico, the ncurses-based editor from the non-free mailer package Pine (itself now available under the Apache License as Alpine).
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-a-stateless-configuration.patch
    %reconfigure --enable-utf8 --docdir=/usr/share/doc/nano
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/nanorc $installdir/usr/share/defaults/nano/nanorc
    # https://github.com/scopatz/nanorc
    for rcFile in $pkgfiles/nanorc-extras/*.nanorc; do
        install -m 00644 $rcFile $installdir/usr/share/nano
    done
