name       : nano
version    : '7.1'
release    : 147
source     :
    - https://www.nano-editor.org/dist/v7/nano-7.1.tar.xz : 57ba751e9b7519f0f6ddee505202e387c75dde440c1f7aa1b9310cc381406836
homepage   : https://www.nano-editor.org
license    : GPL-3.0-or-later
component  : system.devel
summary    : Small, friendly text editor inspired by Pico
description: |
    GNU nano is an easy-to-use text editor originally designed as a replacement for Pico, the ncurses-based editor from the non-free mailer package Pine (itself now available under the Apache License as Alpine).
mancompress: yes
builddeps  :
    - nanorc
rundeps    :
    - nanorc
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-a-stateless-configuration.patch
    %reconfigure --enable-utf8 --docdir=/usr/share/doc/nano
build      : |
    %make
install    : |
    %make_install
    # Include syntax definitions
    for rcfile in $installdir/usr/share/nano/*.nanorc; do
        echo include /usr/share/nano/${rcfile##*nano/} >> $pkgfiles/nanorc
    done
    # Include missing definitions from scopatz's files
    for rcfile in /usr/share/nanorc/*.nanorc; do
        if ! grep -Fq ${rcfile#*highlighting/} $pkgfiles/nanorc
        then
            echo include "$rcfile" >> $pkgfiles/nanorc
        fi
    done
    install -Dm00644 $pkgfiles/nanorc $installdir/usr/share/defaults/nano/nanorc
