name       : nano
version    : 2.5.3
release    : 47
source     :
    - http://www.nano-editor.org/dist/v2.5/nano-2.5.3.tar.gz : b2b060129b9feff2d4870d803a441178c96531de9aed144ec0b83bd63ccb12ee
license    :
    - GPL-3.0
summary    : Small, friendly text editor inspired by Pico
component  : editor
description: |
    GNU nano is an easy-to-use text editor originally designed as a replacement for Pico, the ncurses-based editor from the non-free mailer package Pine (itself now available under the Apache License as Alpine).
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-a-stateless-configuration.patch
    autoreconf -vdi
    %configure --enable-utf8 --docdir=/usr/share/doc/nano
build      : |
    %make
install    : |
    %make_install
    # TODO: Convert to stateless
    install -D -m 00644 $pkgfiles/nanorc $installdir/usr/share/defaults/nano/nanorc
