name       : nano
version    : '6.3'
release    : 137
source     :
    - https://www.nano-editor.org/dist/v6/nano-6.3.tar.xz : eb532da4985672730b500f685dbaab885a466d08fbbf7415832b95805e6f8687
homepage   : https://www.nano-editor.org
license    : GPL-3.0-or-later
component  : system.devel
summary    : Small, friendly text editor inspired by Pico
description: |
    GNU nano is an easy-to-use text editor originally designed as a replacement for Pico, the ncurses-based editor from the non-free mailer package Pine (itself now available under the Apache License as Alpine).
mancompress: yes
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-a-stateless-configuration.patch
    %reconfigure --enable-utf8 --docdir=/usr/share/doc/nano
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/nanorc $installdir/usr/share/defaults/nano/nanorc
    # https://github.com/scopatz/nanorc
    for rcFile in $pkgfiles/nanorc-extras/*.nanorc; do
        install -m 00644 $rcFile $installdir/usr/share/nano
    done
