name       : nano
version    : '5.7'
release    : 126
source     :
    - https://nano-editor.org/dist/v5/nano-5.7.tar.xz : d4b181cc2ec11def3711b4649e34f2be7a668e70ab506860514031d069cccafa
homepage   : https://www.nano-editor.org
license    : GPL-3.0-or-later
component  : system.devel
summary    : Small, friendly text editor inspired by Pico
description: |
    GNU nano is an easy-to-use text editor originally designed as a replacement for Pico, the ncurses-based editor from the non-free mailer package Pine (itself now available under the Apache License as Alpine).
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-a-stateless-configuration.patch
    %reconfigure --enable-utf8 --docdir=/usr/share/doc/nano
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/nanorc $installdir/usr/share/defaults/nano/nanorc
    install -Dm00644 $pkgfiles/git.nanorc $installdir/usr/share/nano/git.nanorc
    # https://github.com/scopatz/nanorc
    for rcFile in $pkgfiles/nanorc-extras/*.nanorc; do
        install -m 00644 $rcFile $installdir/usr/share/nano
    done
