name        : nano
version     : 2.4.3
release     : 38
source     :
    - http://www.nano-editor.org/dist/v2.4/nano-2.4.3.tar.gz : 32d627072b6026678e4f4095c047adec92ac7ec542dd6d91cf27f49b601768f2
license     :
    - GPL-3.0
summary     : Small, friendly text editor inspired by Pico
description : |
    GNU nano is an easy-to-use text editor originally designed as a replacement for Pico, the ncurses-based editor from the non-free mailer package Pine (itself now available under the Apache License as Alpine).
setup      : |
    %configure --enable-utf8 --docdir=/usr/share/doc/nano
build      : |
    %make
install    : |
    %make_install
    # TODO: Convert to stateless
    install -D -m 00644 $pkgfiles/nanorc $installdir/etc/nanorc
