name        : nano
version     : 2.4.1
release     : 26
source      :
    - http://www.nano-editor.org/dist/v2.4/nano-2.4.1.tar.gz : 6a0ceb5e1b9b9bea72d5d1f46488ace4782b1f198ea6ba558480a86d994f29d2
homepage    : http://www.nano-editor.org/
license     :
    - GPL-3.0
summary     : Small, friendly text editor inspired by Pico
description : |
    GNU nano is an easy-to-use text editor originally designed as a replacement for Pico, the ncurses-based editor from the non-free mailer package Pine (itself now available under the Apache License as Alpine).
setup      : |
    %configure --enable-utf8
build      : |
    %make
install    : |
    %make_install
    # TODO: Convert to stateless
    install -D -m 00644 $pkgfiles/nanorc $installdir/etc/nanorc
